language: node_js
dist: trusty
node_js:
  - "10"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npx git+ssh://git@github.ibm.com/maximo-app-framework/flint.git#semver:1 ci-init
script:
  - yarn
  - yarn build:production
deploy:
  skip_cleanup: true
  provider: script
  script: CI=false yarn deploy
  on:
    branch: master
