// istanbul ignore file
/*
 * Licensed Materials - Property of IBM
 *
 * 5724-U18, 5737-M66
 *
 * (C) Copyright IBM Corp. 2023 All Rights Reserved
 *
 * US Government Users Restricted Rights - Use, duplication or
 * disclosure restricted by GSA ADP Schedule Contract with
 * IBM Corp.
 */

/**
 * Mobile MAXVARS
 */
const mobilemaxvars = [
  {
    varname: "ADDRMASTER",
    varvalue: "MAXIMO",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2228,
    vartype: "ORG",
    rowstamp: 805162,
  },
  {
    varname: "ALLOWBLINDCNT",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2350,
    vartype: "ORG",
    rowstamp: 583809,
  },
  {
    varname: "ALLOWRECEIPT",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 685,
    vartype: "ORG",
    rowstamp: 308056,
  },
  {
    varname: "ALLOWSPORDER",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 559,
    vartype: "ORG",
    rowstamp: 307254,
  },
  {
    varname: "AMCREWAVAILFACTOR",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2248,
    vartype: "ORG",
    rowstamp: 307860,
  },
  {
    varname: "ASHIST_ON_WOSTATUS",
    varvalue: "COMPLETE",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 33,
    vartype: "ORG",
    rowstamp: 307102,
  },
  {
    varname: "ASSETDRILLDOWNTOP",
    varvalue: "LOCATION",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 277,
    vartype: "ORG",
    rowstamp: 307285,
  },
  {
    varname: "AUTOAPPRLABINVOICE",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 359,
    vartype: "ORG",
    rowstamp: 307340,
  },
  {
    varname: "AUTOBLANKETPOREL",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 30,
    vartype: "ORG",
    rowstamp: 307099,
  },
  {
    varname: "AUTOCLOSEPO",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 81,
    vartype: "ORG",
    rowstamp: 307151,
  },
  {
    varname: "AUTODELETELOCKOUT",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 32,
    vartype: "ORG",
    rowstamp: 307101,
  },
  {
    varname: "AUTOINVUSE",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 682,
    vartype: "ORG",
    rowstamp: 308054,
  },
  {
    varname: "AUTOPOEXT",
    varvalue: "PRWAPPR",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 27,
    vartype: "ORG",
    rowstamp: 307096,
  },
  {
    varname: "AUTOPOINT",
    varvalue: "POAPPR",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 26,
    vartype: "ORG",
    rowstamp: 307095,
  },
  {
    varname: "A_BREAKPOINT",
    varvalue: "0.800",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 4,
    vartype: "ORG",
    rowstamp: 307076,
  },
  {
    varname: "A_CCF",
    varvalue: "30",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 7,
    vartype: "ORG",
    rowstamp: 307079,
  },
  {
    varname: "B_BREAKPOINT",
    varvalue: "0.150",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 5,
    vartype: "ORG",
    rowstamp: 307077,
  },
  {
    varname: "B_CCF",
    varvalue: "60",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 8,
    vartype: "ORG",
    rowstamp: 307080,
  },
  {
    varname: "CLOSENOINVOICEPO",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 565,
    vartype: "ORG",
    rowstamp: 307106,
  },
  {
    varname: "CLOSENORECEIVEDPO",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 541,
    vartype: "ORG",
    rowstamp: 307228,
  },
  {
    varname: "COMPLETEONFINORDEL",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 72,
    vartype: "ORG",
    rowstamp: 307149,
  },
  {
    varname: "CONTRALINEORLOADED",
    varvalue: "LOADEDCOST",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 857,
    vartype: "ORG",
    rowstamp: 307033,
  },
  {
    varname: "CONTWSTARTAPPR",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 896,
    vartype: "ORG",
    rowstamp: 307552,
  },
  {
    varname: "COORDINATE",
    varvalue: "XY",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2232,
    vartype: "ORG",
    rowstamp: 976168,
  },
  {
    varname: "CRAFTOFASSIGNMENT",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 47,
    vartype: "ORG",
    rowstamp: 307128,
  },
  {
    varname: "CURRLINEORLOADED",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 867,
    vartype: "ORG",
    rowstamp: 307043,
  },
  {
    varname: "C_BREAKPOINT",
    varvalue: "0.050",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 6,
    vartype: "ORG",
    rowstamp: 307078,
  },
  {
    varname: "C_CCF",
    varvalue: "90",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 9,
    vartype: "ORG",
    rowstamp: 307081,
  },
  {
    varname: "DDASSETCOUNT",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 279,
    vartype: "ORG",
    rowstamp: 307287,
  },
  {
    varname: "DISABLEGLSWITCH",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 306,
    vartype: "ORG",
    rowstamp: 307311,
  },
  {
    varname: "DOLINEARRECALIB",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 903,
    vartype: "ORG",
    rowstamp: 307559,
  },
  {
    varname: "DOWNPROMPT",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 21,
    vartype: "ORG",
    rowstamp: 307092,
  },
  {
    varname: "DOWNTIMEDFLTS",
    varvalue: "REPORTED",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 20,
    vartype: "ORG",
    rowstamp: 307091,
  },
  {
    varname: "ELAPSEDHOURS",
    varvalue: "24",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 69,
    vartype: "ORG",
    rowstamp: 307146,
  },
  {
    varname: "EPWRKQUERY",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2258,
    vartype: "ORG",
    rowstamp: 307870,
  },
  {
    varname: "GLCHECKCOA",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 308,
    vartype: "ORG",
    rowstamp: 307313,
  },
  {
    varname: "GLREQUIREDFORTRANS",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 312,
    vartype: "ORG",
    rowstamp: 307317,
  },
  {
    varname: "GLSETDATEFP",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 900,
    vartype: "ORG",
    rowstamp: 307556,
  },
  {
    varname: "GLVALIDATEFP",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 310,
    vartype: "ORG",
    rowstamp: 307315,
  },
  {
    varname: "INCLUDECONSITEMS",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 778,
    vartype: "ORG",
    rowstamp: 307437,
  },
  {
    varname: "INVCEGLPSTDTVALSAV",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 688,
    vartype: "ORG",
    rowstamp: 308059,
  },
  {
    varname: "INVCOUNT",
    varvalue: "ALLITEMS",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2334,
    vartype: "ORG",
    rowstamp: 583713,
  },
  {
    varname: "INVCOUNTNOISSUEDAY",
    varvalue: "30",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2346,
    vartype: "ORG",
    rowstamp: 583728,
  },
  {
    varname: "INVMTOL",
    varvalue: "5.00",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2338,
    vartype: "ORG",
    rowstamp: 583718,
  },
  {
    varname: "INVOICEMGT",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 83,
    vartype: "ORG",
    rowstamp: 307152,
  },
  {
    varname: "INVOICEPOSITEID",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 697,
    vartype: "ORG",
    rowstamp: 308067,
  },
  {
    varname: "INVPOLINERECVCLOSE",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 862,
    vartype: "ORG",
    rowstamp: 307038,
  },
  {
    varname: "INVPTOL",
    varvalue: "5.00",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2342,
    vartype: "ORG",
    rowstamp: 583723,
  },
  {
    varname: "INVREORDERCAT",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 870,
    vartype: "ORG",
    rowstamp: 307046,
  },
  {
    varname: "LABORREQUIRED",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 73,
    vartype: "ORG",
    rowstamp: 307150,
  },
  {
    varname: "LABTRANSTOLERANCE",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 554,
    vartype: "ORG",
    rowstamp: 307268,
  },
  {
    varname: "LABTRNALLOWANYCRFT",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 379,
    vartype: "ORG",
    rowstamp: 307358,
  },
  {
    varname: "LNRASTIGNOREHISTWO",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 874,
    vartype: "ORG",
    rowstamp: 307050,
  },
  {
    varname: "LR_APPR_IN_LABOR",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 34,
    vartype: "ORG",
    rowstamp: 307103,
  },
  {
    varname: "LR_APPR_OUT_LABOR",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 35,
    vartype: "ORG",
    rowstamp: 307104,
  },
  {
    varname: "LR_PO_INLAB_RQRD",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 36,
    vartype: "ORG",
    rowstamp: 307105,
  },
  {
    varname: "LR_PO_OUTLAB_RQRD",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 37,
    vartype: "ORG",
    rowstamp: 307118,
  },
  {
    varname: "MAXCONSINVLINES",
    varvalue: "40",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 775,
    vartype: "ORG",
    rowstamp: 307434,
  },
  {
    varname: "MAXCREATEDITEMS",
    varvalue: "100",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2290,
    vartype: "ORG",
    rowstamp: 574507,
  },
  {
    varname: "MAXPRLINES",
    varvalue: "40",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 12,
    vartype: "ORG",
    rowstamp: 307084,
  },
  {
    varname: "NEGATIVEAVAIL",
    varvalue: "ALLOW",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 66,
    vartype: "ORG",
    rowstamp: 307144,
  },
  {
    varname: "NEGATIVECURBAL",
    varvalue: "DISALLOW",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 65,
    vartype: "ORG",
    rowstamp: 307143,
  },
  {
    varname: "NESTEDJOBPLANS",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 678,
    vartype: "ORG",
    rowstamp: 308050,
  },
  {
    varname: "ORGIGNOREDIAVAIL",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 703,
    vartype: "ORG",
    rowstamp: 308072,
  },
  {
    varname: "ORGIGNORESRMAVAIL",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 700,
    vartype: "ORG",
    rowstamp: 307546,
  },
  {
    varname: "PLUSCACTIVEVAL",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 791,
    vartype: "ORG",
    rowstamp: 307450,
  },
  {
    varname: "PLUSCAPPRTOOLS",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 818,
    vartype: "ORG",
    rowstamp: 307477,
  },
  {
    varname: "PLUSCAUTOSTATUS",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 794,
    vartype: "ORG",
    rowstamp: 307453,
  },
  {
    varname: "PLUSCEDITDATA",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 821,
    vartype: "ORG",
    rowstamp: 307480,
  },
  {
    varname: "PLUSCEXTDATE",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 797,
    vartype: "ORG",
    rowstamp: 307456,
  },
  {
    varname: "PLUSCMOBREADONLY",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 815,
    vartype: "ORG",
    rowstamp: 307474,
  },
  {
    varname: "PLUSCPASTDUEVAL",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 800,
    vartype: "ORG",
    rowstamp: 307459,
  },
  {
    varname: "PLUSCQUALTECH",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 803,
    vartype: "ORG",
    rowstamp: 307462,
  },
  {
    varname: "PLUSCROTASSET",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 824,
    vartype: "ORG",
    rowstamp: 307483,
  },
  {
    varname: "PLUSCTOLWARN",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 806,
    vartype: "ORG",
    rowstamp: 307465,
  },
  {
    varname: "PLUSCVALTOOL",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 809,
    vartype: "ORG",
    rowstamp: 307468,
  },
  {
    varname: "PLUSCWORKTYPECAL",
    varvalue: "CAL",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 812,
    vartype: "ORG",
    rowstamp: 307471,
  },
  {
    varname: "PLUSGDDENSCONST",
    varvalue: "1000000",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2447,
    vartype: null,
    rowstamp: 630711,
  },
  {
    varname: "PLUSGHISTORYPERIOD",
    varvalue: "365",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2443,
    vartype: null,
    rowstamp: 630655,
  },
  {
    varname: "PLUSGHPCALCENABLED",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2460,
    vartype: "ORG",
    rowstamp: 665047,
  },
  {
    varname: "PLUSGMATRIXCALTYPE",
    varvalue: "ASSET",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2427,
    vartype: null,
    rowstamp: 612637,
  },
  {
    varname: "PLUSGMOCREVAPP",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2451,
    vartype: null,
    rowstamp: 634933,
  },
  {
    varname: "PLUSGOVRWRTJPDATA",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2435,
    vartype: null,
    rowstamp: 614511,
  },
  {
    varname: "PLUSGPOPRSKASSESS",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2478,
    vartype: "ORG",
    rowstamp: 693090,
  },
  {
    varname: "PLUSGTGTMINVALUE",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2428,
    vartype: null,
    rowstamp: 612638,
  },
  {
    varname: "PLUSGUSELOGBOOK",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2474,
    vartype: "ORG",
    rowstamp: 692924,
  },
  {
    varname: "PLUSGWORKTYPETRA",
    varvalue: "TRA",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2439,
    vartype: null,
    rowstamp: 624547,
  },
  {
    varname: "POASSETRETVAL",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 781,
    vartype: "ORG",
    rowstamp: 307440,
  },
  {
    varname: "POPNDREVEDIT",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 740,
    vartype: "ORG",
    rowstamp: 307400,
  },
  {
    varname: "PRAPPROVAL",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 19,
    vartype: "ORG",
    rowstamp: 307090,
  },
  {
    varname: "PRCHANGE",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 18,
    vartype: "ORG",
    rowstamp: 307089,
  },
  {
    varname: "PRSPECIALDIRECT",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 67,
    vartype: "ORG",
    rowstamp: 307145,
  },
  {
    varname: "RECEIPLINEORLOADED",
    varvalue: "LINECOST",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 854,
    vartype: "ORG",
    rowstamp: 307821,
  },
  {
    varname: "RESBUFFER",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 694,
    vartype: "ORG",
    rowstamp: 308064,
  },
  {
    varname: "SAEDITABLE",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2236,
    vartype: "ORG",
    rowstamp: 307848,
  },
  {
    varname: "SAMSGPROMPT",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2244,
    vartype: "ORG",
    rowstamp: 307856,
  },
  {
    varname: "SERVRECEIPTDEFAULT",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 354,
    vartype: "ORG",
    rowstamp: 307337,
  },
  {
    varname: "SETACTSTARTONINIT",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 44,
    vartype: "ORG",
    rowstamp: 307125,
  },
  {
    varname: "SETTOREVERSED",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 893,
    vartype: "ORG",
    rowstamp: 307549,
  },
  {
    varname: "SHFTLGHNDOVER",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2483,
    vartype: "ORG",
    rowstamp: 693459,
  },
  {
    varname: "SHIFTENDOFFSET",
    varvalue: "8",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 71,
    vartype: "ORG",
    rowstamp: 307148,
  },
  {
    varname: "SHIFTSTARTOFFSET",
    varvalue: "-4",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 70,
    vartype: "ORG",
    rowstamp: 307147,
  },
  {
    varname: "SHOWDUPATLOC",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 281,
    vartype: "ORG",
    rowstamp: 307289,
  },
  {
    varname: "SHOWDUPWITHASSET",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 283,
    vartype: "ORG",
    rowstamp: 307291,
  },
  {
    varname: "SKIPDUPATLOC",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 42,
    vartype: "ORG",
    rowstamp: 307123,
  },
  {
    varname: "SKIPDUPWITHASSET",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 43,
    vartype: "ORG",
    rowstamp: 307124,
  },
  {
    varname: "STRADDRDETAIL",
    varvalue: "NODETAIL",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2224,
    vartype: "ORG",
    rowstamp: 805158,
  },
  {
    varname: "STREETORDERNUM",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2240,
    vartype: "ORG",
    rowstamp: 307852,
  },
  {
    varname: "TERMSEQINTERVAL",
    varvalue: "10",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 451,
    vartype: "ORG",
    rowstamp: 307515,
  },
  {
    varname: "TERMSEQSEED",
    varvalue: "10",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 453,
    vartype: "ORG",
    rowstamp: 307517,
  },
  {
    varname: "TXFRREQPO",
    varvalue: "NEVER",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 731,
    vartype: "ORG",
    rowstamp: 307391,
  },
  {
    varname: "TXFRREQSHIP",
    varvalue: "ORG",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 728,
    vartype: "ORG",
    rowstamp: 307388,
  },
  {
    varname: "UPDATEGLPSTDATE",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 691,
    vartype: "ORG",
    rowstamp: 307545,
  },
  {
    varname: "UPDATEINVENTORY",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 53,
    vartype: "ORG",
    rowstamp: 307133,
  },
  {
    varname: "USERECEIPTACTDATE",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 760,
    vartype: "ORG",
    rowstamp: 307419,
  },
  {
    varname: "WARREXPDATE",
    varvalue: "1",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 46,
    vartype: "ORG",
    rowstamp: 307127,
  },
  {
    varname: "WOENABLEREPFAC",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 734,
    vartype: "ORG",
    rowstamp: 307394,
  },
  {
    varname: "WONOREPFACWARNING",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 737,
    vartype: "ORG",
    rowstamp: 307397,
  },
  {
    varname: "WORKZONE",
    varvalue: "0",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 2254,
    vartype: "ORG",
    rowstamp: 307866,
  },
  {
    varname: "WOSTATUSCLEARRESV",
    varvalue: "CLOSED",
    orgid: "EAGLENA",
    siteid: null,
    maxvarsid: 61,
    vartype: "ORG",
    rowstamp: 307139,
  },
];

export default mobilemaxvars;
