package com.ibm.maximo.technician.testcases.calibration.tests;

import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.util.Properties;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testng.SkipException;

import com.ibm.maximo.automation.mobile.AbstractAutomationFramework;
import com.ibm.maximo.automation.mobile.api.JdbcConnection;
import com.ibm.maximo.technician.framework.TechnicianTest;

/**
 * This class will be removed soon.
 * @see com.ibm.maximo.technician.testcases.calibration.support.factories.DatasheetFactory#createDataSheet
 */
@Deprecated
public class CreateDataSheet extends TechnicianTest {

	private final static Logger logger = LoggerFactory.getLogger(CreateDataSheet.class);
	public static String functionCheckAssetFunctionName = "Function Checks";
	public static String dynamiCheckAssetFunctionName = "Dynamic Checks";

	public void createMultiAFDataSheet(String configPath, JdbcConnection jdbcConnection, String calAssetID,
			String locationID, String woNum, String siteID, String orgID) throws Exception {

		String dataSheetName = "MULTI_AF_" + AbstractAutomationFramework.randomString(5).toUpperCase();
		logger.info("Create Analog data sheet with multi asset functions...");
		Properties properties = new Properties();
		Object[] resultsObjects;
		Object[] resultArray;
		try {

			BufferedInputStream in = new BufferedInputStream(new FileInputStream(configPath));
			properties.load(in);

			// Create Data sheet
			jdbcConnection.executeUpdateSQL("delete from maximo.PLUSDSPLAN where DSPLANNUM = '" + dataSheetName + "'");

			String insertPLUSDSPLANQuery = "INSERT INTO maximo.PLUSDSPLAN (PLUSDSPLANID,DSPLANNUM,ORGID,SITEID,CHANGEBY,STATUSDATE,CHANGEDATE,DS1,DS2,DS3,DS4,DS5,DS6,DS7,DS8,DS9,DS10,STATUS,HISTORYFLAG,VIEWASLOOP,HASLD,DESCRIPTION,LANGCODE,REVISIONNUM,REVCOMMENTS) VALUES (maximo.PLUSDSPLANSEQ.nextval,'"
					+ dataSheetName + "',NULL,NULL,'" + properties.getProperty("system.username").toUpperCase()
					+ "',sysdate,sysdate,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'APPR',0,0,0,'Dynamic Check DS','EN',0,NULL)";
			jdbcConnection.executeUpdateSQL(insertPLUSDSPLANQuery);
			logger.info("PLUSDSPLAN='" + dataSheetName + "' created successfully...!!!");

			jdbcConnection
					.executeUpdateSQL("delete from maximo.PLUSCDSSTATUS where DSPLANNUM = '" + dataSheetName + "'");
			String insertPLUSCDSSTATUSQuery = "INSERT INTO maximo.PLUSCDSSTATUS (PLUSCDSSTATUSID,DSPLANNUM,STATUS,CHANGEBY,CHANGEDATE,MEMO,ORGID,SITEID,REVISIONNUM) VALUES (maximo.PLUSCDSSTATUSSEQ.nextval,'"
					+ dataSheetName + "','APPR','" + properties.getProperty("system.username").toUpperCase()
					+ "',sysdate,NULL,NULL,NULL,0)";
			jdbcConnection.executeUpdateSQL(insertPLUSCDSSTATUSQuery);
			logger.info("PLUSCDSSTATUS created successfully for '" + dataSheetName + "'...!!!");
			
			//Create PLUSCDSCONFIG entry
			jdbcConnection.executeUpdateSQL("delete from maximo.PLUSCDSCONFIG where DSPLANNUM='" + dataSheetName + "'");
			String insertPLUSCDSCONFIGQuery = "INSERT INTO maximo.PLUSCDSCONFIG (PLUSCDSCONFIGID ,DSPLANNUM, ORGID ,SITEID ,REVISIONNUM ,ASSETERROR ,ASSETNPLACES ,ASSETTRUNCATE ,TOLERROR ,TOLNPLACES ,TOLTRUNCATE ,REPEATVALUE ,STDDEV ,OUTPUTTRUNCATE ,RANGETRUNCATE) VALUES (maximo.PLUSCDSCONFIGSEQ.NEXTVAL,'"
					+ dataSheetName + "',NULL, NULL, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1)";
			jdbcConnection.executeUpdateSQL(insertPLUSCDSCONFIGQuery);
			logger.info("PLUSCDSCONFIG created successfully for '" + dataSheetName + "'...!!!");

			String maxInstrSeq = "select COALESCE(MAX(INSTRSEQ), 1000) from maximo.PLUSCDSINSTR";
			resultsObjects = jdbcConnection.executeSQL(maxInstrSeq);
			resultArray = (Object[]) resultsObjects[0];
			int maxInstrSeqNUMForAnalog = Integer.parseInt(resultArray[0].toString()) + 1;
			logger.info("INSTRSEQAnalog=" + maxInstrSeqNUMForAnalog);

			jdbcConnection
					.executeUpdateSQL("delete from maximo.PLUSCDSINSTR where DSPLANNUM = '" + dataSheetName + "'");
			String insertPLUSCDSINSTRForAnalogQuery = "INSERT INTO maximo.PLUSCDSINSTR (PLUSCDSINSTRID,DSPLANNUM,DESCRIPTION,LANGCODE,ORGID,SITEID,PLANTYPE,INSTRCALRANGEFROM,INSTRCALRANGETO,INSTRCALRANGEEU,INSTROUTRANGEFROM,INSTROUTRANGETO,INSTROUTRANGEEU,INPUTPRECISION,OUTPUTPRECISION,PROCESSEU,PROCESSEUFACTOR,TOL1TYPE,TOL1LOWERVALUE,TOL1UPPERVALUE,TOL2TYPE,TOL2LOWERVALUE,TOL2UPPERVALUE,TOL3TYPE,TOL3LOWERVALUE,TOL3UPPERVALUE,TOL4TYPE,TOL4LOWERVALUE,TOL4UPPERVALUE,RON1TYPE,RON1LOWERVALUE,RON1UPPERVALUE,TOL1STATUS,TOL2STATUS,TOL3STATUS,TOL4STATUS,NOADJMADECHOICE,ALLOWPOINTINSERTS,INSTRSEQ,SQUAREROOT,CLIPLIMITS,TOL1SUMEU,TOL2SUMEU,TOL3SUMEU,TOL4SUMEU,TOL1SUMSPAN,TOL2SUMSPAN,TOL3SUMSPAN,TOL4SUMSPAN,TOL1SUMURV,TOL2SUMURV,TOL3SUMURV,TOL4SUMURV,TOL1SUMREAD,TOL2SUMREAD,TOL3SUMREAD,TOL4SUMREAD,TOL1SUMDIRECTION,TOL2SUMDIRECTION,TOL3SUMDIRECTION,TOL4SUMDIRECTION,TOL1NOADJLIMIT,TOL2NOADJLIMIT,TOL3NOADJLIMIT,TOL4NOADJLIMIT,ASSETFUNCTION,HASLD,TOL1DESCRIPTION,TOL2DESCRIPTION,TOL3DESCRIPTION,TOL4DESCRIPTION,INPUTRANGE,OUTPUTRANGE,NOADJMADECHOICE1,NOADJMADECHOICE2,NOADJMADECHOICE3,NOADJMADECHOICE4,REVISIONNUM,CALPOINT,CALFUNCTION,CALDYNAMIC,MANUAL,NONLINEAR,REPEATABLE,SQUARED,CLIPLIMITSIN) VALUES (maximo.PLUSCDSINSTRSEQ.NEXTVAL,'"
					+ dataSheetName
					+ "','EU Analog Temperature Transmitter 01','EN',NULL,NULL,'ANALOG','100.00','300.00','Deg C','4.00','20.00','mA',2,2,'Deg C',NULL,'EU','-1.00','1.00','EU','-2.00','2.00','EU','-3.00','3.00','EU','-4.00','4.00','EU','-5.00','5.00','PASS','ADJREQD','LIMITEDUSE','FAIL',0,0,"
					+ maxInstrSeqNUMForAnalog
					+ ",0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,1,0,'T1','T2','T3','T4',1,0,1,0,0,0,0,1,0,0,0,0,0,0,0)";
			jdbcConnection.executeUpdateSQL(insertPLUSCDSINSTRForAnalogQuery);

			int maxInstrSeqNUMForFunctionCheck = maxInstrSeqNUMForAnalog + 1;
			logger.info("INSTRSEQFunctionCheck=" + maxInstrSeqNUMForFunctionCheck);
			String insertPLUSCDSINSTRForFunctionCheckQuery = "INSERT INTO maximo.PLUSCDSINSTR (PLUSCDSINSTRID,DSPLANNUM,DESCRIPTION,LANGCODE,ORGID,SITEID,PLANTYPE,INSTRCALRANGEFROM,INSTRCALRANGETO,INSTRCALRANGEEU,INSTROUTRANGEFROM,INSTROUTRANGETO,INSTROUTRANGEEU,INPUTPRECISION,OUTPUTPRECISION,PROCESSEU,PROCESSEUFACTOR,TOL1TYPE,TOL1LOWERVALUE,TOL1UPPERVALUE,TOL2TYPE,TOL2LOWERVALUE,TOL2UPPERVALUE,TOL3TYPE,TOL3LOWERVALUE,TOL3UPPERVALUE,TOL4TYPE,TOL4LOWERVALUE,TOL4UPPERVALUE,RON1TYPE,RON1LOWERVALUE,RON1UPPERVALUE,TOL1STATUS,TOL2STATUS,TOL3STATUS,TOL4STATUS,NOADJMADECHOICE,ALLOWPOINTINSERTS,INSTRSEQ,SQUAREROOT,CLIPLIMITS,TOL1SUMEU,TOL2SUMEU,TOL3SUMEU,TOL4SUMEU,TOL1SUMSPAN,TOL2SUMSPAN,TOL3SUMSPAN,TOL4SUMSPAN,TOL1SUMURV,TOL2SUMURV,TOL3SUMURV,TOL4SUMURV,TOL1SUMREAD,TOL2SUMREAD,TOL3SUMREAD,TOL4SUMREAD,TOL1SUMDIRECTION,TOL2SUMDIRECTION,TOL3SUMDIRECTION,TOL4SUMDIRECTION,TOL1NOADJLIMIT,TOL2NOADJLIMIT,TOL3NOADJLIMIT,TOL4NOADJLIMIT,ASSETFUNCTION,HASLD,TOL1DESCRIPTION,TOL2DESCRIPTION,TOL3DESCRIPTION,TOL4DESCRIPTION,INPUTRANGE,OUTPUTRANGE,NOADJMADECHOICE1,NOADJMADECHOICE2,NOADJMADECHOICE3,NOADJMADECHOICE4,REVISIONNUM,CALPOINT,CALFUNCTION,CALDYNAMIC,MANUAL,NONLINEAR,REPEATABLE,SQUARED,CLIPLIMITSIN) VALUES (maximo.PLUSCDSINSTRSEQ.NEXTVAL,'"
					+ dataSheetName
					+ "','"+ functionCheckAssetFunctionName +"','EN',NULL,NULL,'ANALOG',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,"
					+ maxInstrSeqNUMForFunctionCheck
					+ ",0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,2,0,NULL,NULL,NULL,NULL,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0)";
			jdbcConnection.executeUpdateSQL(insertPLUSCDSINSTRForFunctionCheckQuery);

			int maxInstrSeqNUMForDynamicCheck = maxInstrSeqNUMForFunctionCheck + 1;
			logger.info("INSTRSEQDynamicCheck=" + maxInstrSeqNUMForDynamicCheck);
			String insertPLUSCDSINSTRForDynamicCheckQuery = "INSERT INTO maximo.PLUSCDSINSTR (PLUSCDSINSTRID,DSPLANNUM,DESCRIPTION,LANGCODE,ORGID,SITEID,PLANTYPE,INSTRCALRANGEFROM,INSTRCALRANGETO,INSTRCALRANGEEU,INSTROUTRANGEFROM,INSTROUTRANGETO,INSTROUTRANGEEU,INPUTPRECISION,OUTPUTPRECISION,PROCESSEU,PROCESSEUFACTOR,TOL1TYPE,TOL1LOWERVALUE,TOL1UPPERVALUE,TOL2TYPE,TOL2LOWERVALUE,TOL2UPPERVALUE,TOL3TYPE,TOL3LOWERVALUE,TOL3UPPERVALUE,TOL4TYPE,TOL4LOWERVALUE,TOL4UPPERVALUE,RON1TYPE,RON1LOWERVALUE,RON1UPPERVALUE,TOL1STATUS,TOL2STATUS,TOL3STATUS,TOL4STATUS,NOADJMADECHOICE,ALLOWPOINTINSERTS,INSTRSEQ,SQUAREROOT,CLIPLIMITS,TOL1SUMEU,TOL2SUMEU,TOL3SUMEU,TOL4SUMEU,TOL1SUMSPAN,TOL2SUMSPAN,TOL3SUMSPAN,TOL4SUMSPAN,TOL1SUMURV,TOL2SUMURV,TOL3SUMURV,TOL4SUMURV,TOL1SUMREAD,TOL2SUMREAD,TOL3SUMREAD,TOL4SUMREAD,TOL1SUMDIRECTION,TOL2SUMDIRECTION,TOL3SUMDIRECTION,TOL4SUMDIRECTION,TOL1NOADJLIMIT,TOL2NOADJLIMIT,TOL3NOADJLIMIT,TOL4NOADJLIMIT,ASSETFUNCTION,HASLD,TOL1DESCRIPTION,TOL2DESCRIPTION,TOL3DESCRIPTION,TOL4DESCRIPTION,INPUTRANGE,OUTPUTRANGE,NOADJMADECHOICE1,NOADJMADECHOICE2,NOADJMADECHOICE3,NOADJMADECHOICE4,REVISIONNUM,CALPOINT,CALFUNCTION,CALDYNAMIC,MANUAL,NONLINEAR,REPEATABLE,SQUARED,CLIPLIMITSIN) VALUES (maximo.PLUSCDSINSTRSEQ.NEXTVAL,'"
					+ dataSheetName
					+ "','"+ dynamiCheckAssetFunctionName +"','EN',NULL,NULL,'ANALOG',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,"
					+ maxInstrSeqNUMForDynamicCheck
					+ ",0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,0,0,0,3,0,NULL,NULL,NULL,NULL,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0)";
			jdbcConnection.executeUpdateSQL(insertPLUSCDSINSTRForDynamicCheckQuery);
			logger.info("Multiple PLUSCDSINSTR created successfully for '" + dataSheetName + "'...!!!");

			jdbcConnection
					.executeUpdateSQL("delete from maximo.PLUSCDSPOINT where DSPLANNUM = '" + dataSheetName + "'");

			String insertPLUSCDSPOINTAnalogQuery1 = "INSERT INTO maximo.PLUSCDSPOINT (PLUSCDSPOINTID,DSPLANNUM,ORGID,SITEID,INPUTPERCENT,OUTPUTVALUE,INPUTVALUE,POINT,RON1UPPER,RON1LOWER,TOL1LOWER,TOL1UPPER,TOL2LOWER,TOL2UPPER,TOL3LOWER,TOL3UPPER,TOL4LOWER,TOL4UPPER,SETPOINTACTION,SETPOINTVALUE,PLANTYPE,POINTDESCRIPTION,INSTRSEQ,DIRECTION,HASLD,REVISIONNUM,RON1TYPE,TOLERANCEEU,SETPOINTADJ,CALPOINT,CALFUNCTION,CALDYNAMIC,LANGCODE) VALUES (maximo.PLUSCDSPOINTSEQ.NEXTVAL,'"
					+ dataSheetName
					+ "',NULL,NULL,NULL,'4.00','100.00',1,'105.00','95.00','3.92','4.08','3.84','4.16','3.76','4.24','3.68','4.32',NULL,NULL,'ANALOG','0% Input',"
					+ maxInstrSeqNUMForAnalog + ",'INCREASING',0,0,'EU','mA',0,1,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCDSPOINTAnalogQuery1);

			String insertPLUSCDSPOINTAnalogQuery2 = "INSERT INTO maximo.PLUSCDSPOINT (PLUSCDSPOINTID,DSPLANNUM,ORGID,SITEID,INPUTPERCENT,OUTPUTVALUE,INPUTVALUE,POINT,RON1UPPER,RON1LOWER,TOL1LOWER,TOL1UPPER,TOL2LOWER,TOL2UPPER,TOL3LOWER,TOL3UPPER,TOL4LOWER,TOL4UPPER,SETPOINTACTION,SETPOINTVALUE,PLANTYPE,POINTDESCRIPTION,INSTRSEQ,DIRECTION,HASLD,REVISIONNUM,RON1TYPE,TOLERANCEEU,SETPOINTADJ,CALPOINT,CALFUNCTION,CALDYNAMIC,LANGCODE) VALUES (maximo.PLUSCDSPOINTSEQ.NEXTVAL,'"
					+ dataSheetName
					+ "',NULL,NULL,NULL,'8.00','150.00',2,'155.00','145.00','7.92','8.08','7.84','8.16','7.76','8.24','7.68','8.32',NULL,NULL,'ANALOG','25% Input',"
					+ maxInstrSeqNUMForAnalog + ",'INCREASING',0,0,'EU','mA',0,1,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCDSPOINTAnalogQuery2);

			String insertPLUSCDSPOINTAnalogQuery3 = "INSERT INTO maximo.PLUSCDSPOINT (PLUSCDSPOINTID,DSPLANNUM,ORGID,SITEID,INPUTPERCENT,OUTPUTVALUE,INPUTVALUE,POINT,RON1UPPER,RON1LOWER,TOL1LOWER,TOL1UPPER,TOL2LOWER,TOL2UPPER,TOL3LOWER,TOL3UPPER,TOL4LOWER,TOL4UPPER,SETPOINTACTION,SETPOINTVALUE,PLANTYPE,POINTDESCRIPTION,INSTRSEQ,DIRECTION,HASLD,REVISIONNUM,RON1TYPE,TOLERANCEEU,SETPOINTADJ,CALPOINT,CALFUNCTION,CALDYNAMIC,LANGCODE) VALUES (maximo.PLUSCDSPOINTSEQ.NEXTVAL,'"
					+ dataSheetName
					+ "',NULL,NULL,NULL,'12.00','200.00',3,'205.00','195.00','11.92','12.08','11.84','12.16','11.76','12.24','11.68','12.32',NULL,NULL,'ANALOG','50% Input',"
					+ maxInstrSeqNUMForAnalog + ",'INCREASING',0,0,'EU','mA',0,1,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCDSPOINTAnalogQuery3);

			String insertPLUSCDSPOINTAnalogQuery4 = "INSERT INTO maximo.PLUSCDSPOINT (PLUSCDSPOINTID,DSPLANNUM,ORGID,SITEID,INPUTPERCENT,OUTPUTVALUE,INPUTVALUE,POINT,RON1UPPER,RON1LOWER,TOL1LOWER,TOL1UPPER,TOL2LOWER,TOL2UPPER,TOL3LOWER,TOL3UPPER,TOL4LOWER,TOL4UPPER,SETPOINTACTION,SETPOINTVALUE,PLANTYPE,POINTDESCRIPTION,INSTRSEQ,DIRECTION,HASLD,REVISIONNUM,RON1TYPE,TOLERANCEEU,SETPOINTADJ,CALPOINT,CALFUNCTION,CALDYNAMIC,LANGCODE) VALUES (maximo.PLUSCDSPOINTSEQ.NEXTVAL,'"
					+ dataSheetName
					+ "',NULL,NULL,NULL,'16.00','250.00',4,'255.00','245.00','15.92','16.08','15.84','16.16','15.76','16.24','15.68','16.32',NULL,NULL,'ANALOG','75% Input',"
					+ maxInstrSeqNUMForAnalog + ",'INCREASING',0,0,'EU','mA',0,1,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCDSPOINTAnalogQuery4);

			String insertPLUSCDSPOINTAnalogQuery5 = "INSERT INTO maximo.PLUSCDSPOINT (PLUSCDSPOINTID,DSPLANNUM,ORGID,SITEID,INPUTPERCENT,OUTPUTVALUE,INPUTVALUE,POINT,RON1UPPER,RON1LOWER,TOL1LOWER,TOL1UPPER,TOL2LOWER,TOL2UPPER,TOL3LOWER,TOL3UPPER,TOL4LOWER,TOL4UPPER,SETPOINTACTION,SETPOINTVALUE,PLANTYPE,POINTDESCRIPTION,INSTRSEQ,DIRECTION,HASLD,REVISIONNUM,RON1TYPE,TOLERANCEEU,SETPOINTADJ,CALPOINT,CALFUNCTION,CALDYNAMIC,LANGCODE) VALUES (maximo.PLUSCDSPOINTSEQ.NEXTVAL,'"
					+ dataSheetName
					+ "',NULL,NULL,NULL,'20.00','300.00',5,'305.00','295.00','19.92','20.08','19.84','20.16','19.76','20.24','19.68','20.32',NULL,NULL,'ANALOG','100% Input',"
					+ maxInstrSeqNUMForAnalog + ",'INCREASING',0,0,'EU','mA',0,1,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCDSPOINTAnalogQuery5);
			logger.info(
					"5 PLUSCDSPOINT of Analog asset function created successfully for '" + dataSheetName + "'...!!!");

			String insertPLUSCDSPOINTFunctionCheckQuery1 = "INSERT INTO maximo.PLUSCDSPOINT (PLUSCDSPOINTID,DSPLANNUM,ORGID,SITEID,INPUTPERCENT,OUTPUTVALUE,INPUTVALUE,POINT,RON1UPPER,RON1LOWER,TOL1LOWER,TOL1UPPER,TOL2LOWER,TOL2UPPER,TOL3LOWER,TOL3UPPER,TOL4LOWER,TOL4UPPER,SETPOINTACTION,SETPOINTVALUE,PLANTYPE,POINTDESCRIPTION,INSTRSEQ,DIRECTION,HASLD,REVISIONNUM,RON1TYPE,TOLERANCEEU,SETPOINTADJ,CALPOINT,CALFUNCTION,CALDYNAMIC,LANGCODE) VALUES (maximo.PLUSCDSPOINTSEQ.NEXTVAL,'"
					+ dataSheetName
					+ "',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ANALOG','Function Check 1',"
					+ maxInstrSeqNUMForFunctionCheck + ",NULL,0,0,NULL,NULL,0,0,1,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCDSPOINTFunctionCheckQuery1);

			String insertPLUSCDSPOINTFunctionCheckQuery2 = "INSERT INTO maximo.PLUSCDSPOINT (PLUSCDSPOINTID,DSPLANNUM,ORGID,SITEID,INPUTPERCENT,OUTPUTVALUE,INPUTVALUE,POINT,RON1UPPER,RON1LOWER,TOL1LOWER,TOL1UPPER,TOL2LOWER,TOL2UPPER,TOL3LOWER,TOL3UPPER,TOL4LOWER,TOL4UPPER,SETPOINTACTION,SETPOINTVALUE,PLANTYPE,POINTDESCRIPTION,INSTRSEQ,DIRECTION,HASLD,REVISIONNUM,RON1TYPE,TOLERANCEEU,SETPOINTADJ,CALPOINT,CALFUNCTION,CALDYNAMIC,LANGCODE) VALUES (maximo.PLUSCDSPOINTSEQ.NEXTVAL,'"
					+ dataSheetName
					+ "',NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ANALOG','Function Check 2',"
					+ maxInstrSeqNUMForFunctionCheck + ",NULL,0,0,NULL,NULL,0,0,1,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCDSPOINTFunctionCheckQuery2);

			String insertPLUSCDSPOINTFunctionCheckQuery3 = "INSERT INTO maximo.PLUSCDSPOINT (PLUSCDSPOINTID,DSPLANNUM,ORGID,SITEID,INPUTPERCENT,OUTPUTVALUE,INPUTVALUE,POINT,RON1UPPER,RON1LOWER,TOL1LOWER,TOL1UPPER,TOL2LOWER,TOL2UPPER,TOL3LOWER,TOL3UPPER,TOL4LOWER,TOL4UPPER,SETPOINTACTION,SETPOINTVALUE,PLANTYPE,POINTDESCRIPTION,INSTRSEQ,DIRECTION,HASLD,REVISIONNUM,RON1TYPE,TOLERANCEEU,SETPOINTADJ,CALPOINT,CALFUNCTION,CALDYNAMIC,LANGCODE) VALUES (maximo.PLUSCDSPOINTSEQ.NEXTVAL,'"
					+ dataSheetName
					+ "',NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ANALOG','Function Check 3',"
					+ maxInstrSeqNUMForFunctionCheck + ",NULL,0,0,NULL,NULL,0,0,1,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCDSPOINTFunctionCheckQuery3);
			logger.info("3 PLUSCDSPOINT of Function Check asset function created successfully for '" + dataSheetName
					+ "'...!!!");

			String insertPLUSCDSPOINTDynamicCheckQuery1 = "INSERT INTO maximo.PLUSCDSPOINT (PLUSCDSPOINTID,DSPLANNUM,ORGID,SITEID,INPUTPERCENT,OUTPUTVALUE,INPUTVALUE,POINT,RON1UPPER,RON1LOWER,TOL1LOWER,TOL1UPPER,TOL2LOWER,TOL2UPPER,TOL3LOWER,TOL3UPPER,TOL4LOWER,TOL4UPPER,SETPOINTACTION,SETPOINTVALUE,PLANTYPE,POINTDESCRIPTION,INSTRSEQ,DIRECTION,HASLD,REVISIONNUM,RON1TYPE,TOLERANCEEU,SETPOINTADJ,CALPOINT,CALFUNCTION,CALDYNAMIC,LANGCODE) VALUES (maximo.PLUSCDSPOINTSEQ.NEXTVAL,'"
					+ dataSheetName
					+ "',NULL,NULL,NULL,NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ANALOG','Dynamic Check 1',"
					+ maxInstrSeqNUMForDynamicCheck + ",NULL,0,0,NULL,NULL,0,0,0,1,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCDSPOINTDynamicCheckQuery1);

			String insertPLUSCDSPOINTDynamicCheckQuery2 = "INSERT INTO maximo.PLUSCDSPOINT (PLUSCDSPOINTID,DSPLANNUM,ORGID,SITEID,INPUTPERCENT,OUTPUTVALUE,INPUTVALUE,POINT,RON1UPPER,RON1LOWER,TOL1LOWER,TOL1UPPER,TOL2LOWER,TOL2UPPER,TOL3LOWER,TOL3UPPER,TOL4LOWER,TOL4UPPER,SETPOINTACTION,SETPOINTVALUE,PLANTYPE,POINTDESCRIPTION,INSTRSEQ,DIRECTION,HASLD,REVISIONNUM,RON1TYPE,TOLERANCEEU,SETPOINTADJ,CALPOINT,CALFUNCTION,CALDYNAMIC,LANGCODE) VALUES (maximo.PLUSCDSPOINTSEQ.NEXTVAL,'"
					+ dataSheetName
					+ "',NULL,NULL,NULL,NULL,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ANALOG','Dynamic Check 2',"
					+ maxInstrSeqNUMForDynamicCheck + ",NULL,0,0,NULL,NULL,0,0,0,1,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCDSPOINTDynamicCheckQuery2);

			String insertPLUSCDSPOINTDynamicCheckQuery3 = "INSERT INTO maximo.PLUSCDSPOINT (PLUSCDSPOINTID,DSPLANNUM,ORGID,SITEID,INPUTPERCENT,OUTPUTVALUE,INPUTVALUE,POINT,RON1UPPER,RON1LOWER,TOL1LOWER,TOL1UPPER,TOL2LOWER,TOL2UPPER,TOL3LOWER,TOL3UPPER,TOL4LOWER,TOL4UPPER,SETPOINTACTION,SETPOINTVALUE,PLANTYPE,POINTDESCRIPTION,INSTRSEQ,DIRECTION,HASLD,REVISIONNUM,RON1TYPE,TOLERANCEEU,SETPOINTADJ,CALPOINT,CALFUNCTION,CALDYNAMIC,LANGCODE) VALUES (maximo.PLUSCDSPOINTSEQ.NEXTVAL,'"
					+ dataSheetName
					+ "',NULL,NULL,NULL,NULL,NULL,3,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'ANALOG','Dynamic Check 3',"
					+ maxInstrSeqNUMForDynamicCheck + ",NULL,0,0,NULL,NULL,0,0,0,1,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCDSPOINTDynamicCheckQuery3);
			logger.info("3 PLUSCDSPOINT of Dynamic Check asset function created successfully for '" + dataSheetName
					+ "'...!!!");

			// Assign data sheet to the Work order
			String maxWODSNum = "select COALESCE(MAX(WODSNUM), 1000) FROM maximo.PLUSCWODS";
			resultsObjects = jdbcConnection.executeSQL(maxWODSNum);
			resultArray = (Object[]) resultsObjects[0];
			int WODSNUM = Integer.parseInt(resultArray[0].toString()) + 1;
			logger.info("WODSNUM=" + WODSNUM);

			jdbcConnection.executeUpdateSQL("delete from maximo.PLUSCWODS where DSPLANNUM = '" + dataSheetName + "'");
			String insertPLUSCWODSQuery = "INSERT INTO maximo.PLUSCWODS (PLUSCWODSID,WONUM,SITEID,ORGID,DSPLANNUM,NOADJMADE,VIEWASLOOP,ISADDED,ASSETNUM,REVISIONNUM,DESCRIPTION,ADDINGTOWO,REQUIRED,WODSNUM,HASLD,LANGCODE,TAGLOCATION,REQUIREDALWAYS) VALUES (maximo.PLUSCWODSSEQ.nextval,'"
					+ woNum + "','" + siteID + "','" + orgID + "','" + dataSheetName + "',0,0,1,'" + calAssetID
					+ "',0,'Analog with multi Asset Function Data sheet',0,1," + WODSNUM + ",0,'EN','" + locationID
					+ "',0)";
			jdbcConnection.executeUpdateSQL(insertPLUSCWODSQuery);
			logger.info("PLUSCWODS created successfully for '" + dataSheetName + "'...!!!");

			jdbcConnection
					.executeUpdateSQL("delete from maximo.PLUSCWODSINSTR where DSPLANNUM = '" + dataSheetName + "'");
			String insertPLUSCWODSINSTRAnalogQuery = "INSERT INTO maximo.PLUSCWODSINSTR (PLUSCWODSINSTRID,DSPLANNUM,ASSETNUM,WONUM,WODSNUM,ORGID,SITEID,DESCRIPTION,ALLOWPOINTINSERTS,ASSETFUNCTION,CLIPLIMITS,INPUTPRECISION,INSTRCALRANGEEU,INSTRCALRANGEFROM,INSTRCALRANGETO,INSTROUTRANGEEU,INSTROUTRANGEFROM,INSTROUTRANGETO,INSTRSEQ,NOADJMADE,NOADJMADECHOICE,OUTPUTPRECISION,PLANTYPE,PROCESSEU,PROCESSEUFACTOR,RON1LOWERVALUE,RON1TYPE,RON1UPPERVALUE,SQUAREROOT,TOL1LOWERVALUE,TOL1NOADJLIMIT,TOL1STATUS,TOL1TYPE,TOL1UPPERVALUE,TOL2LOWERVALUE,TOL2NOADJLIMIT,TOL2STATUS,TOL2TYPE,TOL2UPPERVALUE,TOL3LOWERVALUE,TOL3NOADJLIMIT,TOL3STATUS,TOL3TYPE,TOL3UPPERVALUE,TOL4LOWERVALUE,TOL4NOADJLIMIT,TOL4STATUS,TOL4TYPE,TOL4UPPERVALUE,INPUTRANGE,OUTPUTRANGE,TOL1DESCRIPTION,TOL2DESCRIPTION,TOL3DESCRIPTION,TOL4DESCRIPTION,NOADJMADECHOICE1,NOADJMADECHOICE2,NOADJMADECHOICE3,NOADJMADECHOICE4,REVISIONNUM,CALPOINT,CALFUNCTION,CALDYNAMIC,NONLINEAR,REPEATABLE,MANUAL,SQUARED,CLIPLIMITSIN,ASFOUNDERROR,ASLEFTERROR,HASLD,LANGCODE) VALUES (maximo.PLUSCWODSINSTRSEQ.nextval,'"
					+ dataSheetName + "','" + calAssetID + "','" + woNum + "'," + WODSNUM + ",'" + orgID + "','"
					+ siteID
					+ "','EU Analog Temperature Transmitter 01',0,1,0,2,'Deg C','100.00','300.00','mA','4.00','20.00',"
					+ maxInstrSeqNUMForAnalog
					+ ",0,NULL,2,'ANALOG','Deg C',NULL,'-5.00','EU','5.00',0,'-1.00',0,'PASS','EU','1.00','-2.00',0,'ADJREQD','EU','2.00','-3.00',0,'LIMITEDUSE','EU','3.00','-4.00',0,'FAIL','EU','4.00',1,0,'T1','T2','T3','T4',1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCWODSINSTRAnalogQuery);

			String insertPLUSCWODSINSTRFunctionCheckQuery = "INSERT INTO maximo.PLUSCWODSINSTR (PLUSCWODSINSTRID,DSPLANNUM,ASSETNUM,WONUM,WODSNUM,ORGID,SITEID,DESCRIPTION,ALLOWPOINTINSERTS,ASSETFUNCTION,CLIPLIMITS,INPUTPRECISION,INSTRCALRANGEEU,INSTRCALRANGEFROM,INSTRCALRANGETO,INSTROUTRANGEEU,INSTROUTRANGEFROM,INSTROUTRANGETO,INSTRSEQ,NOADJMADE,NOADJMADECHOICE,OUTPUTPRECISION,PLANTYPE,PROCESSEU,PROCESSEUFACTOR,RON1LOWERVALUE,RON1TYPE,RON1UPPERVALUE,SQUAREROOT,TOL1LOWERVALUE,TOL1NOADJLIMIT,TOL1STATUS,TOL1TYPE,TOL1UPPERVALUE,TOL2LOWERVALUE,TOL2NOADJLIMIT,TOL2STATUS,TOL2TYPE,TOL2UPPERVALUE,TOL3LOWERVALUE,TOL3NOADJLIMIT,TOL3STATUS,TOL3TYPE,TOL3UPPERVALUE,TOL4LOWERVALUE,TOL4NOADJLIMIT,TOL4STATUS,TOL4TYPE,TOL4UPPERVALUE,INPUTRANGE,OUTPUTRANGE,TOL1DESCRIPTION,TOL2DESCRIPTION,TOL3DESCRIPTION,TOL4DESCRIPTION,NOADJMADECHOICE1,NOADJMADECHOICE2,NOADJMADECHOICE3,NOADJMADECHOICE4,REVISIONNUM,CALPOINT,CALFUNCTION,CALDYNAMIC,NONLINEAR,REPEATABLE,MANUAL,SQUARED,CLIPLIMITSIN,ASFOUNDERROR,ASLEFTERROR,HASLD,LANGCODE) VALUES (maximo.PLUSCWODSINSTRSEQ.nextval,'"
					+ dataSheetName + "','" + calAssetID + "','" + woNum + "'," + WODSNUM + ",'" + orgID + "','"
					+ siteID + "','"+ functionCheckAssetFunctionName +"',0,2,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,"
					+ maxInstrSeqNUMForFunctionCheck
					+ ",0,NULL,NULL,'ANALOG',NULL,NULL,NULL,NULL,NULL,0,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCWODSINSTRFunctionCheckQuery);

			String insertPLUSCWODSINSTRDynamicCheckQuery = "INSERT INTO maximo.PLUSCWODSINSTR (PLUSCWODSINSTRID,DSPLANNUM,ASSETNUM,WONUM,WODSNUM,ORGID,SITEID,DESCRIPTION,ALLOWPOINTINSERTS,ASSETFUNCTION,CLIPLIMITS,INPUTPRECISION,INSTRCALRANGEEU,INSTRCALRANGEFROM,INSTRCALRANGETO,INSTROUTRANGEEU,INSTROUTRANGEFROM,INSTROUTRANGETO,INSTRSEQ,NOADJMADE,NOADJMADECHOICE,OUTPUTPRECISION,PLANTYPE,PROCESSEU,PROCESSEUFACTOR,RON1LOWERVALUE,RON1TYPE,RON1UPPERVALUE,SQUAREROOT,TOL1LOWERVALUE,TOL1NOADJLIMIT,TOL1STATUS,TOL1TYPE,TOL1UPPERVALUE,TOL2LOWERVALUE,TOL2NOADJLIMIT,TOL2STATUS,TOL2TYPE,TOL2UPPERVALUE,TOL3LOWERVALUE,TOL3NOADJLIMIT,TOL3STATUS,TOL3TYPE,TOL3UPPERVALUE,TOL4LOWERVALUE,TOL4NOADJLIMIT,TOL4STATUS,TOL4TYPE,TOL4UPPERVALUE,INPUTRANGE,OUTPUTRANGE,TOL1DESCRIPTION,TOL2DESCRIPTION,TOL3DESCRIPTION,TOL4DESCRIPTION,NOADJMADECHOICE1,NOADJMADECHOICE2,NOADJMADECHOICE3,NOADJMADECHOICE4,REVISIONNUM,CALPOINT,CALFUNCTION,CALDYNAMIC,NONLINEAR,REPEATABLE,MANUAL,SQUARED,CLIPLIMITSIN,ASFOUNDERROR,ASLEFTERROR,HASLD,LANGCODE) VALUES (maximo.PLUSCWODSINSTRSEQ.nextval,'"
					+ dataSheetName + "','" + calAssetID + "','" + woNum + "'," + WODSNUM + ",'" + orgID + "','"
					+ siteID + "','"+ dynamiCheckAssetFunctionName +"',0,3,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,"
					+ maxInstrSeqNUMForDynamicCheck
					+ ",0,NULL,NULL,'ANALOG',NULL,NULL,NULL,NULL,NULL,0,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,NULL,0,NULL,NULL,NULL,0,0,NULL,NULL,NULL,NULL,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCWODSINSTRDynamicCheckQuery);
			logger.info("Multiple PLUSCWODSINSTR created successfully for '" + dataSheetName + "'...!!!");

			jdbcConnection
					.executeUpdateSQL("delete from maximo.PLUSCWODSPOINT where DSPLANNUM = '" + dataSheetName + "'");

			String insertPLUSCWODSPOINTAnalogQuery1 = "INSERT INTO maximo.PLUSCWODSPOINT (PLUSCWODSPOINTID,WODSNUM,WONUM,DSPLANNUM,ORGID,SITEID,DIRECTION,INPUTVALUE,INSTRSEQ,ISADDED,OUTPUTVALUE,PLANTYPE,POINT,POINTDESCRIPTION,RON1LOWER,RON1UPPER,REVISIONNUM,ASFOUNDPTERROR,ASLEFTPTERROR,SETPOINTADJ,ASFOUNDPASS,ASFOUNDFAIL,ASLEFTPASS,ASLEFTFAIL,ASFOUNDERROR,ASLEFTERROR,ISAVERAGE,HASLD,LANGCODE) VALUES (maximo.PLUSCWODSPOINTSEQ.nextval,"
					+ WODSNUM + ",'" + woNum + "','" + dataSheetName + "','" + orgID + "','" + siteID
					+ "','INCREASING','100.00'," + maxInstrSeqNUMForAnalog
					+ ",0,'4.00','ANALOG',1,'0% of input','95.00','105.00',0,0,0,0,0,0,0,0,0,0,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCWODSPOINTAnalogQuery1);

			String insertPLUSCWODSPOINTAnalogQuery2 = "INSERT INTO maximo.PLUSCWODSPOINT (PLUSCWODSPOINTID,WODSNUM,WONUM,DSPLANNUM,ORGID,SITEID,DIRECTION,INPUTVALUE,INSTRSEQ,ISADDED,OUTPUTVALUE,PLANTYPE,POINT,POINTDESCRIPTION,RON1LOWER,RON1UPPER,REVISIONNUM,ASFOUNDPTERROR,ASLEFTPTERROR,SETPOINTADJ,ASFOUNDPASS,ASFOUNDFAIL,ASLEFTPASS,ASLEFTFAIL,ASFOUNDERROR,ASLEFTERROR,ISAVERAGE,HASLD,LANGCODE) VALUES (maximo.PLUSCWODSPOINTSEQ.nextval,"
					+ WODSNUM + ",'" + woNum + "','" + dataSheetName + "','" + orgID + "','" + siteID
					+ "','INCREASING','150.00'," + maxInstrSeqNUMForAnalog
					+ ",0,'8.00','ANALOG',2,'25% Input','145.00','155.00',0,0,0,0,0,0,0,0,0,0,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCWODSPOINTAnalogQuery2);

			String insertPLUSCWODSPOINTAnalogQuery3 = "INSERT INTO maximo.PLUSCWODSPOINT (PLUSCWODSPOINTID,WODSNUM,WONUM,DSPLANNUM,ORGID,SITEID,DIRECTION,INPUTVALUE,INSTRSEQ,ISADDED,OUTPUTVALUE,PLANTYPE,POINT,POINTDESCRIPTION,RON1LOWER,RON1UPPER,REVISIONNUM,ASFOUNDPTERROR,ASLEFTPTERROR,SETPOINTADJ,ASFOUNDPASS,ASFOUNDFAIL,ASLEFTPASS,ASLEFTFAIL,ASFOUNDERROR,ASLEFTERROR,ISAVERAGE,HASLD,LANGCODE) VALUES (maximo.PLUSCWODSPOINTSEQ.nextval,"
					+ WODSNUM + ",'" + woNum + "','" + dataSheetName + "','" + orgID + "','" + siteID
					+ "','INCREASING','200.00'," + maxInstrSeqNUMForAnalog
					+ ",0,'12.00','ANALOG',3,'50% Input','195.00','205.00',0,0,0,0,0,0,0,0,0,0,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCWODSPOINTAnalogQuery3);

			String insertPLUSCWODSPOINTAnalogQuery4 = "INSERT INTO maximo.PLUSCWODSPOINT (PLUSCWODSPOINTID,WODSNUM,WONUM,DSPLANNUM,ORGID,SITEID,DIRECTION,INPUTVALUE,INSTRSEQ,ISADDED,OUTPUTVALUE,PLANTYPE,POINT,POINTDESCRIPTION,RON1LOWER,RON1UPPER,REVISIONNUM,ASFOUNDPTERROR,ASLEFTPTERROR,SETPOINTADJ,ASFOUNDPASS,ASFOUNDFAIL,ASLEFTPASS,ASLEFTFAIL,ASFOUNDERROR,ASLEFTERROR,ISAVERAGE,HASLD,LANGCODE) VALUES (maximo.PLUSCWODSPOINTSEQ.nextval,"
					+ WODSNUM + ",'" + woNum + "','" + dataSheetName + "','" + orgID + "','" + siteID
					+ "','INCREASING','250.00'," + maxInstrSeqNUMForAnalog
					+ ",0,'16.00','ANALOG',4,'75% Input','245.00','255.00',0,0,0,0,0,0,0,0,0,0,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCWODSPOINTAnalogQuery4);

			String insertPLUSCWODSPOINTAnalogQuery5 = "INSERT INTO maximo.PLUSCWODSPOINT (PLUSCWODSPOINTID,WODSNUM,WONUM,DSPLANNUM,ORGID,SITEID,DIRECTION,INPUTVALUE,INSTRSEQ,ISADDED,OUTPUTVALUE,PLANTYPE,POINT,POINTDESCRIPTION,RON1LOWER,RON1UPPER,REVISIONNUM,ASFOUNDPTERROR,ASLEFTPTERROR,SETPOINTADJ,ASFOUNDPASS,ASFOUNDFAIL,ASLEFTPASS,ASLEFTFAIL,ASFOUNDERROR,ASLEFTERROR,ISAVERAGE,HASLD,LANGCODE) VALUES (maximo.PLUSCWODSPOINTSEQ.nextval,"
					+ WODSNUM + ",'" + woNum + "','" + dataSheetName + "','" + orgID + "','" + siteID
					+ "','INCREASING','300.00'," + maxInstrSeqNUMForAnalog
					+ ",0,'20.00','ANALOG',5,'100% Input','295.00','305.00',0,0,0,0,0,0,0,0,0,0,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCWODSPOINTAnalogQuery5);
			logger.info(
					"5 PLUSCWODSPOINT of Analog asset function created successfully for '" + dataSheetName + "'...!!!");

			String insertPLUSCWODSPOINTFunctionCheckQuery1 = "INSERT INTO maximo.PLUSCWODSPOINT (PLUSCWODSPOINTID,WODSNUM,WONUM,DSPLANNUM,ORGID,SITEID,DIRECTION,INPUTVALUE,INSTRSEQ,ISADDED,OUTPUTVALUE,PLANTYPE,POINT,POINTDESCRIPTION,RON1LOWER,RON1UPPER,REVISIONNUM,ASFOUNDPTERROR,ASLEFTPTERROR,SETPOINTADJ,ASFOUNDPASS,ASFOUNDFAIL,ASLEFTPASS,ASLEFTFAIL,ASFOUNDERROR,ASLEFTERROR,ISAVERAGE,HASLD,LANGCODE) VALUES (maximo.PLUSCWODSPOINTSEQ.nextval,"
					+ WODSNUM + ",'" + woNum + "','" + dataSheetName + "','" + orgID + "','" + siteID + "',NULL,NULL,"
					+ maxInstrSeqNUMForFunctionCheck
					+ ",0,NULL,'ANALOG',1,'Function Check 1',NULL,NULL,0,0,0,0,0,0,0,0,0,0,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCWODSPOINTFunctionCheckQuery1);

			String insertPLUSCWODSPOINTFunctionCheckQuery2 = "INSERT INTO maximo.PLUSCWODSPOINT (PLUSCWODSPOINTID,WODSNUM,WONUM,DSPLANNUM,ORGID,SITEID,DIRECTION,INPUTVALUE,INSTRSEQ,ISADDED,OUTPUTVALUE,PLANTYPE,POINT,POINTDESCRIPTION,RON1LOWER,RON1UPPER,REVISIONNUM,ASFOUNDPTERROR,ASLEFTPTERROR,SETPOINTADJ,ASFOUNDPASS,ASFOUNDFAIL,ASLEFTPASS,ASLEFTFAIL,ASFOUNDERROR,ASLEFTERROR,ISAVERAGE,HASLD,LANGCODE) VALUES (maximo.PLUSCWODSPOINTSEQ.nextval,"
					+ WODSNUM + ",'" + woNum + "','" + dataSheetName + "','" + orgID + "','" + siteID + "',NULL,NULL,"
					+ maxInstrSeqNUMForFunctionCheck
					+ ",0,NULL,'ANALOG',2,'Function Check 2',NULL,NULL,0,0,0,0,0,0,0,0,0,0,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCWODSPOINTFunctionCheckQuery2);

			String insertPLUSCWODSPOINTFunctionCheckQuery3 = "INSERT INTO maximo.PLUSCWODSPOINT (PLUSCWODSPOINTID,WODSNUM,WONUM,DSPLANNUM,ORGID,SITEID,DIRECTION,INPUTVALUE,INSTRSEQ,ISADDED,OUTPUTVALUE,PLANTYPE,POINT,POINTDESCRIPTION,RON1LOWER,RON1UPPER,REVISIONNUM,ASFOUNDPTERROR,ASLEFTPTERROR,SETPOINTADJ,ASFOUNDPASS,ASFOUNDFAIL,ASLEFTPASS,ASLEFTFAIL,ASFOUNDERROR,ASLEFTERROR,ISAVERAGE,HASLD,LANGCODE) VALUES (maximo.PLUSCWODSPOINTSEQ.nextval,"
					+ WODSNUM + ",'" + woNum + "','" + dataSheetName + "','" + orgID + "','" + siteID + "',NULL,NULL,"
					+ maxInstrSeqNUMForFunctionCheck
					+ ",0,NULL,'ANALOG',3,'Function Check 3',NULL,NULL,0,0,0,0,0,0,0,0,0,0,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCWODSPOINTFunctionCheckQuery3);
			logger.info("3 PLUSCWODSPOINT of Function Check asset function created successfully for '" + dataSheetName
					+ "'...!!!");

			String insertPLUSCWODSPOINTDynamicCheckQuery1 = "INSERT INTO maximo.PLUSCWODSPOINT (PLUSCWODSPOINTID,WODSNUM,WONUM,DSPLANNUM,ORGID,SITEID,DIRECTION,INPUTVALUE,INSTRSEQ,ISADDED,OUTPUTVALUE,PLANTYPE,POINT,POINTDESCRIPTION,RON1LOWER,RON1UPPER,REVISIONNUM,ASFOUNDPTERROR,ASLEFTPTERROR,SETPOINTADJ,ASFOUNDPASS,ASFOUNDFAIL,ASLEFTPASS,ASLEFTFAIL,ASFOUNDERROR,ASLEFTERROR,ISAVERAGE,HASLD,LANGCODE) VALUES (maximo.PLUSCWODSPOINTSEQ.nextval,"
					+ WODSNUM + ",'" + woNum + "','" + dataSheetName + "','" + orgID + "','" + siteID + "',NULL,NULL,"
					+ maxInstrSeqNUMForDynamicCheck
					+ ", 0,NULL,'ANALOG',1,'Dynamic Check 1',NULL,NULL,0,0,0,0,0,0,0,0,0,0,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCWODSPOINTDynamicCheckQuery1);

			String insertPLUSCWODSPOINTDynamicCheckQuery2 = "INSERT INTO maximo.PLUSCWODSPOINT (PLUSCWODSPOINTID,WODSNUM,WONUM,DSPLANNUM,ORGID,SITEID,DIRECTION,INPUTVALUE,INSTRSEQ,ISADDED,OUTPUTVALUE,PLANTYPE,POINT,POINTDESCRIPTION,RON1LOWER,RON1UPPER,REVISIONNUM,ASFOUNDPTERROR,ASLEFTPTERROR,SETPOINTADJ,ASFOUNDPASS,ASFOUNDFAIL,ASLEFTPASS,ASLEFTFAIL,ASFOUNDERROR,ASLEFTERROR,ISAVERAGE,HASLD,LANGCODE) VALUES (maximo.PLUSCWODSPOINTSEQ.nextval,"
					+ WODSNUM + ",'" + woNum + "','" + dataSheetName + "','" + orgID + "','" + siteID + "',	NULL,NULL,"
					+ maxInstrSeqNUMForDynamicCheck
					+ ",0,NULL,'ANALOG',2,'Dynamic Check 2',NULL,NULL,0,0,0,0,0,0,0,0,0,0,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCWODSPOINTDynamicCheckQuery2);

			String insertPLUSCWODSPOINTDynamicCheckQuery3 = "INSERT INTO maximo.PLUSCWODSPOINT (PLUSCWODSPOINTID,WODSNUM,WONUM,DSPLANNUM,ORGID,SITEID,DIRECTION,INPUTVALUE,INSTRSEQ,ISADDED,OUTPUTVALUE,PLANTYPE,POINT,POINTDESCRIPTION,RON1LOWER,RON1UPPER,REVISIONNUM,ASFOUNDPTERROR,ASLEFTPTERROR,SETPOINTADJ,ASFOUNDPASS,ASFOUNDFAIL,ASLEFTPASS,ASLEFTFAIL,ASFOUNDERROR,ASLEFTERROR,ISAVERAGE,HASLD,LANGCODE) VALUES (maximo.PLUSCWODSPOINTSEQ.nextval,"
					+ WODSNUM + ",'" + woNum + "','" + dataSheetName + "','" + orgID + "','" + siteID + "',NULL,NULL,"
					+ maxInstrSeqNUMForDynamicCheck
					+ ",0,NULL,'ANALOG',3,'Dynamic Check 3',NULL,NULL,0,0,0,0,0,0,0,0,0,0,0,0,'EN')";
			jdbcConnection.executeUpdateSQL(insertPLUSCWODSPOINTDynamicCheckQuery3);
			logger.info("3 PLUSCWODSPOINT of Dynamic Check asset function created successfully for '" + dataSheetName
					+ "'...!!!");

			System.setProperty("Multi_AF_DatasheetName", dataSheetName);
			logger.info("Multi asset function Datasheet[" + dataSheetName + "] created and assigned to WO[" + woNum
					+ "] successfully in database...!!!");

		} catch (Exception e) {
			e.printStackTrace();
			throw new SkipException("Unable to create data sheet in DB....!!!");
		}

	}

}
